---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# {ggtrace}

<!-- badges: start -->
`r lifecycle::badge('experimental')`
<!-- badges: end -->

An experimental package for programmatically debugging ggproto methods with `trace()`.

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("yjunechoe/ggtrace")
```

## Usage

```{r setup}
library(ggtrace)
library(ggplot2) # v3.3.5
```

### Example 1 - PositionJitter$compute_layer {ggplot2}

```{r ex-1-setup}
jitter_plot <- ggplot(diamonds[1:1000,], aes(cut, depth)) +
  geom_point(position = position_jitter(width = 0.2, seed = 2021))
jitter_plot
```

```{r ex-1-ggbody}
ggbody(PositionJitter$compute_layer)
```

```{r ex-1-ggtrace, fig.show='hide'}
ggtrace(
  method = PositionJitter$compute_layer,
  trace_steps = c(1, 1, 8, 12),
  trace_exprs = rlang::exprs(
    head(data),   # What does the data passed in look like?
    params,       # What do the initial parameters look like?
    head(~line),  # What is this `dummy_data` thing on Step 8?
    head(~line)   # What does the last line evaluate to?
                  # - i.e., what is returned by the method?
  )
)
jitter_plot # plot not printed to save space
```

### Example 2 - StatSina$compute_panel {ggforce}

```{r ex-2-setup}
library(ggforce)

sina_plot <- ggplot(diamonds[diamonds$cut == "Good",][1:25,], aes(cut, depth)) +
  geom_violin() +
  geom_sina(seed = 2021)
sina_plot
```

```{r ex-2-ggbody}
ggbody(StatSina$compute_panel)
```

```{r ex-2-ggtrace, fid.show = 'hide'}
ggtrace(
  method = "compute_panel",
  obj = StatSina,
  trace_steps = c(1, 12),
  trace_exprs = rlang::expr(data), # evaluated at Step 1 and Step 12
  .print = FALSE
)
sina_plot # plot not printed to save space

# Sometimes doesn't automatically untrace so this may be required
untrace("compute_panel", where = StatSina)
```

```{r ex-2-lastggtrace}
last_ggtrace()
```


