---
title: "Usecase: aes evaluation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Usecase: aes evaluation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Under construction

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ggtrace)
library(ggplot2)
```

## Sneak peak:

https://ggplot2.tidyverse.org/reference/aes_eval.html

How can I know the transformed variables that I can reference inside `after_stat()` and `after_scale()`?

- **after_stat**: `Layer$compute_statistic` 
- **after_scale**: `Geom$use_defaults (Step 6)` - https://github.com/tidyverse/ggplot2/blob/87e9b85dd9f2a294f339d88a353d0c11c851489d/R/geom-.r#L124-L150

<!--

```{r}
ggtrace_aes <- function(context) {
  params <- switch(context,
    "stage" = list(
      "layer_data",
      2,
      quote(~step),
      ggplot2:::Layer
    ),
    "after_stat" = list(
      "compute_statistic",
      5,
      quote(~step),
      ggplot2:::Layer
    ),
    "after_scale" = list(
      "use_defaults",
      7,
      quote(data),
      ggplot2::Geom
    )
  )
  ggtrace(
    method = params[[1]],
    trace_steps = params[[2]],
    trace_exprs =  params[[3]],
    obj = params[[4]]
  )
}
```


# example... abt after scale

```{r, include = FALSE}

switch()

ggbody(Geom$use_defaults)

ggtrace(Geom$use_defaults, 6:7, quote(data))

ggplot(mpg, aes(class, hwy)) +
  geom_boxplot(aes(colour = class, fill = after_scale(alpha(colour, 0.4))))
```

# example... abt after stat

We need to trace Layer but it's internal... -- but that's okay!

`ggbody()` is written such that it parses everything to the left of `$` and sets the result as the ggproto object.

```{r, include = FALSE}
ggplot(mpg, aes(displ)) +
  geom_histogram(aes(y = after_stat(count / max(count))))
```


# notes....

an aside on color<->colour

It did use to error while the PR was under review - https://github.com/tidyverse/ggplot2/pull/3534#issuecomment-533784628
ggplot actually always does this, so it was just a matter of this new `"mapped"` aesthetic getting standardized as well - https://github.com/tidyverse/ggplot2/blob/b5606624cbd3cc5bb09fe2e008d1fada82daf44e/R/aes.r#L150-L163

hexadecimals
```{r include = FALSE}
strtoi(c("0x00", "0x80", "0xFF"))
```
-->
