# Lightweight workflow to test against development version of ggplot2
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    # Run every week
    - cron: '0 0 * * 1'

name: test-with-dev-ggplot2

jobs:
  test-with-dev-ggplot2:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::remotes, any::Hmisc
          needs: check

      # Install development version of ggplot2
      - name: Install dev version of ggplot2
        run: |
          remotes::install_github("tidyverse/ggplot2")
          cat(remotes:::local_sha("ggplot2"))
        shell: Rscript {0}

      # Run tests
      - name: Check package
        run: |
          rcmdcheck::rcmdcheck(
            args = c("--no-manual", "--as-cran"),
            error_on = "warning",
            check_dir = "check"
          )
        shell: Rscript {0}

      # Only print test failures
      - name: Show test failures
        if: failure()
        run: |
          find check -name "*.Rout" -exec cat '{}' \; || true
        shell: bash
